### ISSUE TITLE
CvPagination arrow icons are black on dark mode when active

### ISSUE THREAD

**Issue by thehowl** [carbon-design-system/carbon-components-vue#1113]
```
    "@carbon/icons-vue": "^10.25.0",
    "@carbon/themes": "^10.16.0",
    "@carbon/vue": "^2.37.1",
```

As well as on the demo website here: http://vue.carbondesignsystem.com/?path=/story/components-cvpagination--default

Setting the theme to one of the dark themes makes the arrow black by default. On analysis, this seems to be caused by the fact the icon has the parameter `fill="currentColor"`, which because the button text is of that dark grey color, causes the button to be that color as well.

![image](https://user-images.githubusercontent.com/4681308/107623524-bdf87d00-6c59-11eb-88fa-9c1da5ea8d09.png)

Tested on:

```
Chromium 88.0.4324.150
Mozilla Firefox 85.0.1
```

Vue version should be 2.6.12.

Temporary workaround:

```css
.bx--pagination__button:not(:disabled) > .bx--pagination__button-icon {
  fill: rgb(244, 244, 244);
  color: rgb(244, 244, 244);
}
```
