### ISSUE TITLE
Switching Themes without recompiling

### ISSUE THREAD

**Issue by christianlmc** [carbon-design-system/carbon-components-vue#942]
## Summary
I'm looking for a way to switch themes using :root css variables.

I have read the whole documentation and looked up everywhere but I can't seem to find a way to make the user change the theme on the fly, all I seen is how to set the global theme like this:

``` scss
@import "@carbon/themes/scss/themes";

// Use the gray 10 theme
$carbon--theme: $carbon--theme--g10;
@include carbon--theme();
// Use the gray 90 theme
$carbon--theme: $carbon--theme--g90;
@include carbon--theme();
// Use the gray 100 theme
$carbon--theme: $carbon--theme--g100;
@include carbon--theme();
// import Carbon styles here
@import "carbon-components/scss/globals/scss/styles.scss";
```

## Relevant information

Here you can change the theme on the dropdown menu
https://carbon-components-react.netlify.app/?path=/story/search--default

![image](https://user-images.githubusercontent.com/24314863/86651876-46bf8400-bfba-11ea-88f6-63fe245c4525.png)

**Comment by dcwarwick** [comment]
@christianlmc To change the Carbon theme on the fly currently requires using the "feature flag" `enable-custom-css-properties`. You can then pass an extra parameter `$emit-custom-properties: true` to those calls to `@include carbon-theme();` and they will cause the themes to be set by custom CSS properties rather than baked in to the CSS.

Here's an example:

```scss
$feature-flags: (
    enable-css-custom-properties: true
);

@import "~@carbon/themes/scss";

// Use the gray 10 theme by default
$carbon--theme: $carbon--theme--g10;

// Use the white theme wherever this class is added
.make-the-carbon-theme-go-white {
  @include carbon--theme($theme: $carbon--theme--white, $emit-custom-properties: true);
}

// Use the g100 theme wherever this class is added
.make-the-carbon-theme-go-really-dark {
  @include carbon--theme($theme: $carbon--theme--g100, $emit-custom-properties: true);
}
```

You can see an example of this here:
   https://pages.github.ibm.com/dave-clark/carbon-theme-tune/#/test
On that page, you can use the selector to choose a theme which gets applied to the div with some form fields in it. This selector just adds a different class to the div, according to what you select, defined as above. Notice that the on-the-fly theme applies only within that div: everything else that doesn't get an override applied continues to use the "baked-in" theme (g10 in this case).

I hope that helps.
